### ISSUE TITLE
Aspect from ItemStack not working again. (sorry)

### ISSUE THREAD

**Issue by Arrahis** [Buuz135/Thaumic-JEI#10]
Recently I switched to version 1.10.2 and I do not know much about it. Also, I do not understand programming, but I really need your help. In the game, when I want to do research, there are no block-containing aspects. If only Thaumcraft and JEI are standing, everything works, but as soon as I put more than 15 jar files, this panel stops working. In the log, if you need it: 
[fml-client-latest.log](https://github.com/Buuz135/Thaumic-JEI/files/1821383/fml-client-latest.log)

Please tell me in detail what to do!

**Comment by boosterdev** [comment]
it seems mcjtylib is missing,
[McJtyLib](https://minecraft.curseforge.com/projects/mcjtylib)

**Comment by QuImUfu** [comment]
ok... this is the bug i deemed only theoretically possible with the current build.
this is caused by JEI taking 2mins! to build the item filter.
````
JEI/JEI]: Built	item filter in 126060 ms
````
This build:
https://dl.dropbox.com/s/5mq54id43i3czn4/ThaumicJEI-1.10.2-1.1.3.jar

Is from my fork. It has a config option to disable threading. Enable that option. It will prevent that bug by slowing loading down by ~6s (in you case, will become more if you add mods).
However it should only increase the loading time once that much with the same mods. Afterward it should use a disk cache. If you add a mod it will recalculate the aspects of everything.

Any issues you might experience with this build (even if they seem like a thaumcraft bug) are probably my fault and should only be reported to:
https://github.com/QuImUfu/Thaumic-JEI/issues

@boosterdev is probably right as well and you should install mcjtylib but that has nothing to do with Aspect from ItemStack not working.

**Comment by Arrahis** [comment]
I installed this ThaumicJEI and minecraft disease was sick. As I already mentioned, I do not understand anything in programming. Help to solve the problem, please. I waited a long time to enjoy Thaumcraft fashion. I beg you.
Here is crash report:
[crash-2018-03-17_13.50.59-client.txt](https://github.com/Buuz135/Thaumic-JEI/files/1821476/crash-2018-03-17_13.50.59-client.txt)
And log:
[fml-client-latest.log](https://github.com/Buuz135/Thaumic-JEI/files/1821479/fml-client-latest.log)
Could you teach me to identify these problems?)

**Comment by Arrahis** [comment]
Please forgive me, but I just restarted and ALL WORKS! Thank you very much! I sit with tears of joy in my eyes. Now I also love you guys! Thank you again.

**Comment by Arrahis** [comment]
It's very inconvenient for me to take your time, but it does not work again. I put the complete assembly, as before I identified the problem, and again I do not see in which blocks there is an aspect of Air for example.
Here is the log: 
[fml-client-latest.log](https://github.com/Buuz135/Thaumic-JEI/files/1821507/fml-client-latest.log)

**Comment by QuImUfu** [comment]
Have you set the config option B:disableThreading to true? 
The log indicates you have not.

**Comment by Arrahis** [comment]
Thanks again. So embarrassing.
